name: Benchmark
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  benchmarks:
    name: Benchmarks
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js & pnpm
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          runtime: node@26
          cache: true

      - name: Setup benchmarks
        run: node --run bench:setup

      - name: Run benchmarks
        run: node --run bench
