name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  biome:
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1

      - name: Run Biome
        run: biome ci

  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js & pnpm
        uses: pnpm/setup@v2
        with:
          runtime: node@26
          cache: true

      - name: Run tests
        run: node --run test:coverage

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

<<<<<<< Updated upstream
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Install Node 26
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
=======
      - name: Setup Node.js & pnpm
        uses: pnpm/setup@v2
>>>>>>> Stashed changes
        with:
          runtime: node@26
          cache: true

      - name: Run TypeScript compiler
        run: node --run typecheck
